# Path: /root/begasist/Dockerfile.dev
FROM node:20-alpine

WORKDIR /app

# Cache de dependencias
COPY package.json pnpm-lock.yaml ./
RUN corepack enable && corepack prepare pnpm@10.12.3 --activate
RUN pnpm install

# Código (se puede sobreescribir con volume en compose.dev)
COPY . .

EXPOSE 3000
ENV NODE_ENV=development

# Servir en 0.0.0.0 para acceder desde host/otros contenedores
CMD ["pnpm", "dev", "-p", "3000", "-H", "0.0.0.0"]
