// Path: /root/begasist/types/poi.ts

export type POIType = "event" | "attraction";

export type POICategory = string;
export type POITag = string;

export type POILocation = {
  name?: string; // venue or place name
  address?: string;
  country?: string;
  adminArea1?: string; // province/state/department
  adminArea2?: string; // municipality/county (if applicable)
  locality?: string; // city/locality
  lat?: number;
  lng?: number;
  mapsUrl?: string;
};

export type POIRecord = {
  /**
   * Primary document id generated by Astra.
   * In ingestion flows this can be omitted on insert.
   */
  _id?: string;
  type: POIType;
  name: string;
  summary?: string;
  description?: string;
  categories?: POICategory[];
  tags?: POITag[];
  location?: POILocation;
  // Events only
  startsAt?: string; // ISO-8601 (UTC)
  endsAt?: string;   // ISO-8601 (UTC)
  startDate?: string; // ISO-8601 (UTC) - alias explícito
  endDate?: string;   // ISO-8601 (UTC) - alias explícito
  // Source identity
  sourceId: string;
  sourceUrl?: string;
  externalId?: string | number;
  // Region scoping (e.g., "maldonado_uy") for shared attractions/events
  region?: string;
};

export type ManualPOIRecord = POIRecord & {
  sourceId: "manual";
};
