// @ts-nocheck
import { Metadata } from "next";
import localFont from "next/font/local"; // ✅ Importación correcta


import "./globals.css";

const inter = localFont({
  src: "../public/fonts/geist-latin.woff2", // ✅ Ruta corregida
  variable: "--font-inter",
});

const robotoMono = localFont({
  src: "../public/fonts/geist-mono-latin.woff2", // ✅ Ruta corregida
  variable: "--font-roboto-mono",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
